[package]
name = "binary_diagnostic"
version = "0.1.0"
authors = ["lordidiot <calvin@arthurfong.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
